# Spectral OpenAPI Linting Rules
# https://meta.stoplight.io/docs/spectral/

extends: [[spectral:oas, all]]

rules:
  # Relax some rules for documentation repo
  info-contact: warn
  info-description: warn
  operation-description: warn
  operation-operationId-unique: error
  operation-tags: warn
  tag-description: off
  
  # Enforce critical rules
  oas3-api-servers: error
  oas3-valid-media-example: error
  oas3-valid-schema-example: error
  operation-success-response: error
  no-$ref-siblings: error
  
  # Security
  oas3-operation-security-defined: warn

